import { api } from '../lib/api.js';
import { esc, safeUrl, num, date, icon, repoCard, saveButton, skeleton, empty, errorView, tile, notice, backLink } from '../lib/ui.js';
export async function developer(ctx, username) {
  ctx.render(skeleton());
  try {
    const { profile: p, repos, stats } = await api(`/api/dev/${encodeURIComponent(username)}`, { signal: ctx.signal });
    const top = [...repos].sort((a, b) => b.stargazers_count - a.stargazers_count);
    ctx.render(`${backLink()}<section class="profile-head"><img class="avatar lg" src="${safeUrl(p.avatar_url)}" alt="${esc(p.login)}"><div class="min-w-0 flex-1"><p class="mb-2 text-sm text-neutral-500">@${esc(p.login)}</p><h1>${esc(p.name || p.login)}</h1><p class="muted mt-3 max-w-2xl">${esc(p.bio || 'This developer hasn’t added a bio yet.')}</p><div class="row mt-4 text-xs text-neutral-500">${p.location ? `<span class="inline-flex items-center gap-1">${icon('location')}${esc(p.location)}</span>` : ''}${p.company ? `<span>${esc(p.company)}</span>` : ''}<span>Joined ${date(p.created_at)}</span></div></div><div class="row">${saveButton('dev', p.login, p.login, { avatar_url: p.avatar_url, url: p.html_url })}<a class="btn btn-ghost" href="${safeUrl(p.html_url)}" target="_blank" rel="noopener noreferrer">GitHub profile ${icon('external')}</a></div></section>
    <div class="tiles">${tile('Followers', p.followers)}${tile('Public repositories', p.public_repos)}${tile('Stars across analyzed repos', stats.totalStars)}${tile('Forks across analyzed repos', stats.totalForks)}</div>
    ${!stats.reposAvailable ? notice('Repository statistics are temporarily unavailable. Retry to load them.') : stats.sampled ? notice(`Statistics cover the ${stats.analyzedRepos} most recently updated repositories out of ${p.public_repos} public repositories.`) : ''}
    ${(stats.topLanguages || []).length ? `<section class="card mb-8"><h3>Languages they build with</h3><p class="mt-2 text-xs text-neutral-500">Primary languages by repository count in this sample</p><div class="row mt-4">${stats.topLanguages.map(l => `<span class="pill">${esc(l.language)} <span class="text-neutral-200">${l.count}</span></span>`).join('')}</div></section>` : ''}
    <div class="section-head"><div><h2>Repositories</h2><p>Ordered by stars within the analyzed sample</p></div><span class="pill">${repos.length} projects</span></div><div class="cards">${top.map(repoCard).join('') || empty('No repositories to show', stats.reposAvailable ? 'This developer has no public repositories.' : 'Repository data could not be loaded. Please retry.')}</div>`);
  } catch (error) { if (error.name !== 'AbortError') ctx.render(errorView(error)); }
}
export async function repository(ctx, owner, name) {
  ctx.render(skeleton());
  try {
    const d = await api(`/api/repo/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`, { signal: ctx.signal });
    const r = d.repo;
    const status = d.sectionStatus || {};
    const max = Math.max(1, ...d.activity.map(a => a.commits));
    const activityTotal = d.activity.reduce((sum, a) => sum + a.commits, 0);
    ctx.render(`${backLink()}<section class="flex flex-wrap items-start justify-between gap-5"><div class="min-w-0"><div class="row mb-4"><span class="pill">${icon('repo')} Public repository</span>${r.archived ? '<span class="pill">Archived</span>' : ''}${r.license ? `<span class="pill">${esc(r.license.spdx_id)}</span>` : ''}</div><p class="mb-2 text-neutral-500">${esc(owner)} /</p><h1 class="break-all">${esc(name)}</h1><p class="muted mt-4 max-w-2xl">${esc(r.description || 'No description provided.')}</p><div class="row mt-4">${(r.topics || []).slice(0, 6).map(t => `<a class="pill" href="#/?q=${encodeURIComponent('topic:' + t)}">${esc(t)}</a>`).join('')}</div></div><div class="row">${saveButton('repo', r.full_name, r.full_name, { stars: r.stargazers_count, description: r.description, url: r.html_url })}<a class="btn btn-ghost" href="${safeUrl(r.html_url)}" target="_blank" rel="noopener noreferrer">View on GitHub ${icon('external')}</a></div></section>
    <div class="tiles">${tile('Stars', r.stargazers_count)}${tile('Forks', r.forks_count)}${tile('Open issues & PRs', r.open_issues_count)}${tile('Watchers', r.subscribers_count)}</div>
    <div class="compare-cols"><section class="card"><div class="section-head"><h2>Language breakdown</h2>${icon('code')}</div><p class="text-xs text-neutral-500">Share of source code, measured in bytes</p>${status.languages === 'unavailable' ? notice('Language data is temporarily unavailable. Please retry.') : d.languageDistribution.length ? d.languageDistribution.map(l => `<div class="lang-row"><span>${esc(l.language)}</span><div class="bar"><i style="width:${Number(l.percent)}%"></i></div><span class="text-right">${Number(l.percent)}%</span></div>`).join('') : '<p class="muted mt-5">No language data reported.</p>'}</section>
    <section class="card"><div class="section-head"><h2>Commit activity</h2>${icon('activity')}</div><p class="text-xs text-neutral-500">${status.activity === 'ready' ? `${num(activityTotal)} commits across ${d.activity.length} weeks` : 'Weekly repository activity'}</p>${status.activity === 'pending' ? notice('GitHub is preparing these statistics. Try again in a moment.') : status.activity === 'unavailable' ? notice('Activity data is temporarily unavailable. Please retry.') : d.activity.length ? `<div class="chart" role="img" aria-label="${activityTotal} commits across ${d.activity.length} weeks">${d.activity.map(a => `<i style="height:${Math.max(1, a.commits / max * 100)}%" title="${date(a.week * 1000)}: ${a.commits} commits"></i>`).join('')}</div><div class="chart-caption"><span>${date(d.activity[0].week * 1000)}</span><span>${date(d.activity.at(-1).week * 1000)}</span></div><details class="mt-4 text-xs text-neutral-500"><summary class="cursor-pointer">View activity as text</summary><ul class="mt-3 max-h-40 overflow-y-auto">${d.activity.map(a => `<li>${date(a.week * 1000)}: ${a.commits} commits</li>`).join('')}</ul></details>` : '<p class="muted mt-5">No activity reported for this repository.</p>'}${status.activity !== 'ready' ? '<button class="btn btn-ghost mt-4" data-retry>Refresh analytics</button>' : ''}</section></div>
    <div class="compare-cols mt-5"><section class="card"><div class="section-head"><h2>The people behind it</h2><span class="pill">Top contributors</span></div>${status.contributors === 'unavailable' ? notice('Contributor information is temporarily unavailable.') : d.contributors.map(c => `<a class="flex items-center gap-3 border-b border-line py-3 last:border-0" href="#/dev/${esc(c.login)}"><img class="avatar sm" src="${safeUrl(c.avatar_url)}" alt="" loading="lazy"><span class="flex-1 text-sm">${esc(c.login)}</span><span class="text-xs text-neutral-500">${num(c.contributions)} contributions</span></a>`).join('') || '<p class="muted">No contributors reported.</p>'}</section>
    <section class="card"><div class="section-head"><h2>Recent open discussions</h2><span class="pill">Issues & PRs</span></div>${status.issues === 'unavailable' ? notice('Issue information is temporarily unavailable.') : d.openIssues.map(issue => `<a href="${safeUrl(issue.html_url)}" target="_blank" rel="noopener noreferrer" class="block border-b border-line py-3 last:border-0"><h3 class="text-sm">${esc(issue.title)}</h3><p class="mt-2 text-xs text-neutral-500">#${esc(issue.number)} ${issue.pull_request ? 'Pull request' : 'Issue'} · ${date(issue.created_at)}</p></a>`).join('') || '<p class="muted">No open discussions.</p>'}<p class="mt-4 text-[11px] text-neutral-500">Last pushed ${date(r.pushed_at)}</p></section></div>`);
  } catch (error) { if (error.name !== 'AbortError') ctx.render(errorView(error)); }
}
